services:
  mysql:
    image: mysql:5.7
    container_name: wordpress_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: example_password
    volumes:
      - mysql_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.2-fpm-alpine  # Use a PHP-FPM image
    container_name: wordpress_app
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: example_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini

  nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - wordpress_data:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  mysql_data:
  wordpress_data:
